name: Tests
on:
  push:
    branches:
    - master
    - dev
  # pull_request:

jobs:
  unit-test:
    name: Unit tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-18.04, windows-2019, macos-10.15]
        os: [ubuntu-18.04]
    steps:
    # Set up Flutter.
    - name: Setup Flutter environment
      uses: subosito/flutter-action@4389e6cbc6cb8a4b18c628ff96ff90be0e926aa8
      with:
        channel: master
    - run: flutter doctor -v

    # Checkout gallery code and get packages.
    - name: Checkout GitHub Action code
      uses: actions/checkout@v2
    - run: flutter pub get

    # Analyze, check formatting, and run unit tests.
    - name: Analyze the project
      run: flutter analyze
    - name: Check the format
      run: flutter format --set-exit-if-changed --dry-run .
    - name: Run unit tests
      run: flutter test

    # TODO: publish to pub.dev
    - name: Check before publish to pub.dev
      run: dart pub publish --dry-run
    - name: Publish a new version to pub.dev
      run: dart pub publish -y